name: Publish Module to Azure DevOps Artifacts

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Module Folder
        run: |
          pwd
          ls -la
          ls -la rg_module

      - name: Install Azure DevOps Extension
        run: |
          az extension add --name azure-devops --yes

      - name: Configure Azure DevOps
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.ADO_PAT }}
        run: |
          az devops configure \
            --defaults \
            organization=https://dev.azure.com/${{ secrets.ADO_ORG }} \
            project=${{ secrets.ADO_PROJECT }}

      - name: Publish Terraform Module
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.ADO_PAT }}
        run: |
          az artifacts universal publish \
            --organization "https://dev.azure.com/${{ secrets.ADO_ORG }}" \
            --project "${{ secrets.ADO_PROJECT }}" \
            --scope project \
            --feed "${{ secrets.ADO_FEED }}" \
            --name "rg-module" \
            --version "1.0.${{ github.run_number }}" \
            --description "Terraform Resource Group Module" \
            --path "./rg_module"
