name: Publish Module to Azure DevOps Artifacts

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Zip Terraform Module
        run: |
          zip -r rg-module.zip rg_module/

      - name: Install Azure CLI extension for artifacts
        run: |
          az extension add --name azure-devops

      - name: Login to Azure DevOps
        run: |
          echo "${{ secrets.ADO_PAT }}" | az devops login

      - name: Set default config
        run: |
          az devops configure --defaults organization=https://dev.azure.com/${{ secrets.ADO_ORG }} project=${{ secrets.ADO_PROJECT }}

      - name: Publish to Azure Artifacts Feed
        run: |
          az artifacts universal publish \
            --feed "${{ secrets.ADO_FEED }}" \
            --name "rg-module" \
            --version "1.0.${{ github.run_number }}" \
            --description "Terraform RG Module" \
            --path rg-module.zip
